name: gravemind  # the name of the snap
version: 0.1  # the version of the snap
summary: Web dashboard for Keystroke  # 79 char long summary
description: A web server that serves the contents of a Keystroke report  # a longer description for the snap
confinement: strict  # use "strict" to enforce system access only via declared interfaces

apps:
    gravemind:
        command: ./bin/gravemind
        daemon: simple
        plugs: [network, network-bind]

parts:
    gravemind-server:  # Replace with a part name of your liking
        # Get more information about plugins by running
        # snapcraft help plugins
        # and more information about the available plugins
        # by running
        # snapcraft list-plugins
        plugin: go
        source: ./
